### ISSUE TITLE
'dict' object has no attribute 'iteritems' - error when generating report

### ISSUE THREAD

**Issue by AJIeho4ka** [burke-software/django-report-builder#100]
Fix found

replace "iteritems" with "__iter__" in views.py at lines:
449
506
524
575
577
597

AttributeError at /report_builder/ajax_preview/
'dict' object has no attribute 'iteritems'

Request Method: POST
Request URL: http://127.0.0.1:8000/report_builder/ajax_preview/
Django Version: 1.6.2
Python Executable: C:\Python33\python.exe
Python Version: 3.3.3
Python Path: ['E:\\py projects\\printer_db', 'C:\\Windows\\SYSTEM32\\python33.zip', 'C:\\Python33\\DLLs', 'C:\\Python33\\lib', 'C:\\Python33', 'C:\\Users\\Alex\\AppData\\Roaming\\Python\\Python33\\site-packages', 'C:\\Python33\\lib\\site-packages']
Server time: Thu, 20 Feb 2014 21:35:17 +0200
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'printer_info',
 'south',
 'report_builder')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')

Traceback:
File "C:\Python33\lib\site-packages\django\core\handlers\base.py" in get_response
  114.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "C:\Python33\lib\site-packages\django\contrib\admin\views\decorators.py" in _checklogin
  17.             return view_func(request, *args, **kwargs)
File "C:\Python33\lib\site-packages\report_builder\views.py" in ajax_preview
  643.     objects_list, message = report_to_list(report, request.user, preview=True)
File "C:\Python33\lib\site-packages\report_builder\views.py" in report_to_list
  448.             for position, property_path in property_list.iteritems():

Exception Type: AttributeError at /report_builder/ajax_preview/
Exception Value: 'dict' object has no attribute 'iteritems'
Request information:
GET: No GET data

POST:
report_id = '1'
csrfmiddlewaretoken = 'XzueZdEhYABojR3EL1jtKvMeUAHc5wTd'

FILES: No FILES data

COOKIES:
csrftoken = 'XzueZdEhYABojR3EL1jtKvMeUAHc5wTd'
sessionid = 'gusveygkns1l5uybmcdkavovbfe6phgb'

META:
wsgi.version = 
MOZ_PLUGIN_PATH = 'C:\\Program Files (x86)\\Foxit Software\\Foxit Reader\\plugins\\'
APPDATA = 'C:\\Users\\Alex\\AppData\\Roaming'
GATEWAY_INTERFACE = 'CGI/1.1'
FP_NO_HOST_CHECK = 'NO'
WINDIR = 'C:\\Windows'
HTTP_ACCEPT_LANGUAGE = 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3'
NUMBER_OF_PROCESSORS = '8'
wsgi.run_once = False
HOMEDRIVE = 'C:'
SYSTEMDRIVE = 'C:'
wsgi.multiprocess = False
PROCESSOR_LEVEL = '6'
REMOTE_HOST = ''
CONTENT_TYPE = 'application/x-www-form-urlencoded; charset=UTF-8'
HTTP_ACCEPT_ENCODING = 'gzip, deflate'
OS = 'Windows_NT'
PUBLIC = 'C:\\Users\\Public'
USERPROFILE = 'C:\\Users\\Alex'
COMMONPROGRAMW6432 = 'C:\\Program Files\\Common Files'
PROMPT = '$P$G'
COMSPEC = 'C:\\Windows\\system32\\cmd.exe'
HTTP_X_REQUESTED_WITH = 'XMLHttpRequest'
PROGRAMDATA = 'C:\\ProgramData'
USERNAME = 'Alex'
LOGONSERVER = '\\\\ALEX-PC'
PATH_INFO = '/report_builder/ajax_preview/'
HTTP_HOST = '127.0.0.1:8000'
wsgi.multithread = True
SERVER_NAME = 'Alex-pc'
HTTP_ACCEPT = '*/*'
wsgi.file_wrapper = ''
PATHEXT = '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC'
wsgi.errors = <_io.TextIOWrapper name='' mode='w' encoding='cp866'>
HTTP_CACHE_CONTROL = 'no-cache'
HTTP_CONNECTION = 'keep-alive'
HTTP_PRAGMA = 'no-cache'
TEMP = 'C:\\Users\\Alex\\AppData\\Local\\Temp'
REMOTE_ADDR = '127.0.0.1'
CONTENT_LENGTH = '64'
wsgi.input = <_io.BufferedReader name=32>
HTTP_USER_AGENT = 'Mozilla/5.0 (Windows NT 6.3; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0'
PROCESSOR_ARCHITECTURE = 'AMD64'
HTTP_REFERER = 'http://127.0.0.1:8000/report_builder/report/1/'
COMMONPROGRAMFILES(X86) = 'C:\\Program Files (x86)\\Common Files'
LOCALAPPDATA = 'C:\\Users\\Alex\\AppData\\Local'
CSRF_COOKIE = 'XzueZdEhYABojR3EL1jtKvMeUAHc5wTd'
wsgi.url_scheme = 'http'
ALLUSERSPROFILE = 'C:\\ProgramData'
PROGRAMW6432 = 'C:\\Program Files'
HOMEPATH = '\\Users\\Alex'
USERDOMAIN_ROAMINGPROFILE = 'Alex-pc'
RUN_MAIN = 'true'
HTTP_COOKIE = 'csrftoken=XzueZdEhYABojR3EL1jtKvMeUAHc5wTd; sessionid=gusveygkns1l5uybmcdkavovbfe6phgb'
USERDOMAIN = 'Alex-pc'
TMP = 'C:\\Users\\Alex\\AppData\\Local\\Temp'
PSMODULEPATH = 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\'
COMPUTERNAME = 'ALEX-PC'
SERVER_SOFTWARE = 'WSGIServer/0.2'
SCRIPT_NAME = ''
SERVER_PORT = '8000'
SYSTEMROOT = 'C:\\Windows'
PROGRAMFILES = 'C:\\Program Files'
PROCESSOR_REVISION = '3a09'
SERVER_PROTOCOL = 'HTTP/1.1'
COMMONPROGRAMFILES = 'C:\\Program Files\\Common Files'
DJANGO_SETTINGS_MODULE = 'printer_db.settings'
PROCESSOR_IDENTIFIER = 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel'
REQUEST_METHOD = 'POST'
AMDAPPSDKROOT = 'C:\\Program Files (x86)\\AMD APP\\'
PROGRAMFILES(X86) = 'C:\\Program Files (x86)'
QUERY_STRING = ''
PATH = 'C:\\Program Files (x86)\\AMD APP\\bin\\x86_64;C:\\Program Files (x86)\\AMD APP\\bin\\x86;C:\\Python33\\;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Toshiba\\Bluetooth Toshiba Stack\\sys\\;C:\\Program Files (x86)\\Toshiba\\Bluetooth Toshiba Stack\\sys\\x64\\;C:\\Program Files (x86)\\ATI Technologies\\ATI.ACE\\Core-Static'

Settings:
Using settings module printer_db.settings
DEFAULT_CONTENT_TYPE = 'text/html'
REPORT_BUILDER_INCLUDE = ['printer']
SERVER_EMAIL = 'root@localhost'
DATE_FORMAT = 'N j, Y'
FILE_UPLOAD_HANDLERS = 
MEDIA_ROOT = ''
DATABASE_ROUTERS = []
DEFAULT_FROM_EMAIL = 'webmaster@localhost'
DEFAULT_EXCEPTION_REPORTER_FILTER = 'django.views.debug.SafeExceptionReporterFilter'
ADMINS = 
FIRST_DAY_OF_WEEK = 0
FILE_UPLOAD_PERMISSIONS = None
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
MEDIA_URL = ''
YEAR_MONTH_FORMAT = 'F Y'
DECIMAL_SEPARATOR = '.'
INTERNAL_IPS = 
STATICFILES_FINDERS = 
CACHE_MIDDLEWARE_KEY_PREFIX = '********************'
EMAIL_SUBJECT_PREFIX = '[Django] '
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_NAME = 'sessionid'
SESSION_CACHE_ALIAS = 'default'
TEMPLATE_CONTEXT_PROCESSORS = 
ADMIN_FOR = 
TIME_INPUT_FORMATS = 
EMAIL_USE_TLS = False
SIGNING_BACKEND = 'django.core.signing.TimestampSigner'
LANGUAGES_BIDI = 
FIXTURE_DIRS = 
EMAIL_HOST = 'localhost'
LANGUAGE_CODE = 'en-us'
LOGIN_URL = '/accounts/login/'
PREPEND_WWW = False
TEMPLATE_STRING_IF_INVALID = ''
FILE_UPLOAD_TEMP_DIR = None
DATABASES = {'default': {'NAME': 'E:\\py projects\\printer_db\\db.sqlite3', 'ENGINE': 'django.db.backends.sqlite3', 'TEST_MIRROR': None, 'ATOMIC_REQUESTS': False, 'TIME_ZONE': 'Europe/Riga', 'TEST_COLLATION': None, 'CONN_MAX_AGE': 0, 'AUTOCOMMIT': True, 'TEST_CHARSET': None, 'USER': '', 'TEST_NAME': None, 'HOST': '', 'PORT': '', 'OPTIONS': {}, 'PASSWORD': '********************'}}
TEMPLATE_DEBUG = True
USE_THOUSAND_SEPARATOR = False
TRANSACTIONS_MANAGED = False
LOGGING_CONFIG = 'django.utils.log.dictConfig'
USE_TZ = False
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440
DEFAULT_TABLESPACE = ''
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
X_FRAME_OPTIONS = 'SAMEORIGIN'
FORMAT_MODULE_PATH = None
DATETIME_FORMAT = 'N j, Y, P'
SESSION_COOKIE_HTTPONLY = True
EMAIL_PORT = 25
LOGOUT_URL = '/accounts/logout/'
SESSION_COOKIE_AGE = 1209600
SESSION_COOKIE_PATH = '/'
MIDDLEWARE_CLASSES = 
DISALLOWED_USER_AGENTS = 
SHORT_DATE_FORMAT = 'm/d/Y'
LANGUAGE_COOKIE_NAME = 'django_language'
USE_I18N = True
ALLOWED_INCLUDE_ROOTS = 
SECRET_KEY = '********************'
ABSOLUTE_URL_OVERRIDES = {}
APPEND_SLASH = True
PASSWORD_HASHERS = '********************'
COMMENTS_ALLOW_PROFANITIES = False
CACHE_MIDDLEWARE_SECONDS = 600
STATICFILES_DIRS = 
CSRF_COOKIE_HTTPONLY = False
DATETIME_INPUT_FORMATS = 
SECURE_PROXY_SSL_HEADER = None
THOUSAND_SEPARATOR = ','
EMAIL_HOST_PASSWORD = '********************'
EMAIL_HOST_USER = ''
PROFANITIES_LIST = '********************'
DEBUG_PROPAGATE_EXCEPTIONS = False
USE_L10N = True
CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
USE_X_FORWARDED_HOST = False
DEFAULT_INDEX_TABLESPACE = ''
SETTINGS_MODULE = 'printer_db.settings'
SESSION_COOKIE_SECURE = False
USE_ETAGS = False
CSRF_COOKIE_DOMAIN = None
FILE_CHARSET = 'utf-8'
LANGUAGES = 
TIME_ZONE = 'Europe/Riga'
SESSION_FILE_PATH = None
SHORT_DATETIME_FORMAT = 'm/d/Y P'
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
INSTALLED_APPS = 
DEBUG = True
SEND_BROKEN_LINK_EMAILS = False
LOGGING = {}
STATIC_ROOT = None
TEMPLATE_LOADERS = 
FORCE_SCRIPT_NAME = None
DEFAULT_CHARSET = 'utf-8'
SESSION_SAVE_EVERY_REQUEST = False
NUMBER_GROUPING = 0
PASSWORD_RESET_TIMEOUT_DAYS = '********************'
TEST_RUNNER = 'django.test.runner.DiscoverRunner'
CACHE_MIDDLEWARE_ALIAS = 'default'
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'
LOCALE_PATHS = 
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
MESSAGE_STORAGE = 'django.contrib.messages.storage.fallback.FallbackStorage'
TEMPLATE_DIRS = 
ALLOWED_HOSTS = ['*']
LOGIN_REDIRECT_URL = '/accounts/profile/'
MANAGERS = 
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
CSRF_COOKIE_NAME = 'csrftoken'
MONTH_DAY_FORMAT = 'F j'
WSGI_APPLICATION = 'printer_db.wsgi.application'
STATIC_URL = '/static/'
CSRF_COOKIE_PATH = '/'
TIME_FORMAT = 'P'
IGNORABLE_404_URLS = 
CSRF_COOKIE_SECURE = False
AUTHENTICATION_BACKENDS = 'django.contrib.auth.backends.ModelBackend'
ROOT_URLCONF = 'printer_db.urls'
AUTH_USER_MODEL = 'auth.User'
DATE_INPUT_FORMATS = 
BASE_DIR = 'E:\\py projects\\printer_db'

**Comment by bufke** [comment]
Reopen is still a problem.
