### ISSUE TITLE
Management command to generate and save report, without browser

### ISSUE THREAD

**Issue by noxxan** [burke-software/django-report-builder#121]
For a big amount of data I think it would be useful if I can generate specified report using dedicated management command (like a "save_report" or something).

I saw that for this case there is a Celery based solution, but sometimes it's hard to get Celery into production environment and maintain it.

This feature looks to be not to complicated to be done and I would find it useful, maybe others too?

I would be happy to think about it more deeply if you want?

**Comment by bufke** [comment]
Would accept a pull request or if you wanted to pay for it. Otherwise closing.
