### ISSUE TITLE
REPORT_BUILDER_ASYNC_REPORT doesn't default to False

### ISSUE THREAD

**Issue by james1924** [burke-software/django-report-builder#132]
Could you please add some additional documentation in *settings.py* for:

1. What the syntax should be for including/excluding whole models

2. What the syntax should be for including/excluding model properties

3. REPORT_BUILDER_ASYNC_REPORT (*i.e.* that it has to be set explicitly, and doesn't default to *False*)

Thanks as always for this fantastic app!

**Comment by bufke** [comment]
Will do - that should default to False - I'll look at it. Pull requests always welcome.

**Comment by leebrooks0** [comment]
```AttributeError at /report_builder/

'Settings' object has no attribute 'REPORT_BUILDER_ASYNC_REPORT'```

I had to explicitly set it to false...
