### ISSUE TITLE
Document the fact that Django REST Framework needs to be set up

### ISSUE THREAD

**Issue by ebrelsford** [burke-software/django-report-builder#135]
This isn't mentioned in the documentation, but if the project isn't using Django REST Framework when django-report-builder is installed, the former has to be configured for the latter to work.

**Comment by bufke** [comment]
How's this? https://github.com/burke-software/django-report-builder/blob/master/docs/quickstart.md#requirements

**Comment by ebrelsford** [comment]
Thanks, it's a good start!

I'd consider adding it to the step-by-step directions. Django REST Framework is great and widely used, but there'll be plenty of projects where this is a new requirement. Saying "don't forget to pip install and add rest_framework to INSTALLED_APPS..." really would've gone a long way for me.

**Comment by ulyssesv** [comment]
It is also required to add `'rest_framework.authentication.SessionAuthentication'` to `REST_FRAMEWORK['DEFAULT_AUTHENTICATION_CLASSES']`, otherwise you get the following bug:

```
**ValueError at /report_builder/api/report/**
Cannot assign "<django.contrib.auth.models.AnonymousUser object at 0x1084defd0>": "Report.user_created" must be a "User" instance.
```

I've sent a pull request with a suggestion in the documentation. Thank you for your work!
