### ISSUE TITLE
Can't add a filter

### ISSUE THREAD

**Issue by mau21mau** [burke-software/django-report-builder#139]
Hi! I can't add any filter to my reports. Do you have any idea what could be happening? It only shows an empty canvas.

![image](https://cloud.githubusercontent.com/assets/1305414/6632125/cec8cbf6-c90f-11e4-9a80-3cc29139d35a.png)

**Comment by bufke** [comment]
I'm not sure - those console warnings aren't related. Make sure you are on the latest version. If there is something I can do reopen the issue.
