### ISSUE TITLE
Doesn't "just work" with some DRF default permission classes

### ISSUE THREAD

**Issue by leebrooks0** [burke-software/django-report-builder#140]
Root model is blank until i comment out all my existing DRF settings:

```
# REST_FRAMEWORK = {
#     # Use Django's standard `django.contrib.auth` permissions,
#     # or allow read-only access for unauthenticated users.
#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
#     ),
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework.authentication.TokenAuthentication',
#         'rest_framework.authentication.SessionAuthentication',
#     ),
#     'DEFAULT_RENDERER_CLASSES': (
#         'rest_framework.renderers.JSONRenderer',
#         'rest_framework.renderers.BrowsableAPIRenderer',
#     ),
#     'TEST_REQUEST_DEFAULT_FORMAT': 'json'
# }
```

![model](https://cloud.githubusercontent.com/assets/2501773/6668046/a419d5e4-cbf8-11e4-996b-f3fc256b15a1.png)

Is it possible to get them playing nicely together, I would want want to be able to restrict my reports by role/group...

**Comment by bufke** [comment]
Yeah that is an issue. It would be good to support as many use cases as possible. Do you have any idea on what the conflict is and how to work around it? Is it DEFAULT_PERMISSION_CLASSES? If so we could override that on the report builder api views. However it wouldn't fulfill "restrict my reports by role/group". If you can submit a pull request that supports either default permission class - I'd be happy to merge it.

**Comment by dparizek** [comment]
I was able to see the root model populated, but not access/see the fields list for the root model until I commented out DEFAULT_PERMISSION_CLASSES:

    REST_FRAMEWORK = {
        'DEFAULT_MODEL_SERIALIZER_CLASS': 'rest_framework.serializers.HyperlinkedModelSerializer',
        'DEFAULT_AUTHENTICATION_CLASSES': (
            'rest_framework.authentication.SessionAuthentication',
        ),
        # 'DEFAULT_PERMISSION_CLASSES': (
        #     'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
        # )
    }

**Comment by leebrooks0** [comment]
Here is what the dev tools shows me:

```
TypeError at /report_builder/api/report/

'type' object is not iterable

Request Method: 	OPTIONS
Request URL: 	http://127.0.0.1:8000/report_builder/api/report/
Django Version: 	1.7.4
Exception Type: 	TypeError
Exception Value: 	

'type' object is not iterable

Exception Location: 	/home/lee/Code/cas/venv/lib/python3.4/site-packages/rest_framework/views.py in get_permissions, line 234
Python Executable: 	/home/lee/Code/cas/venv/bin/python
Python Version: 	3.4.2
Python Path: 	

['/home/lee/Code/cas',
 '/home/lee/.pyenv/versions/3.4.2/lib/python34.zip',
 '/home/lee/.pyenv/versions/3.4.2/lib/python3.4',
 '/home/lee/.pyenv/versions/3.4.2/lib/python3.4/plat-linux',
 '/home/lee/.pyenv/versions/3.4.2/lib/python3.4/lib-dynload',
 '/home/lee/Code/cas/venv/lib/python3.4/site-packages']

Server time: 	Tue, 17 Mar 2015 11:31:23 +0000```
```

and 

```python
Traceback Switch to copy-and-paste view

    /home/lee/Code/cas/venv/lib/python3.4/site-packages/django/core/handlers/base.py in get_response

                            response = middleware_method(request, callback, callback_args, callback_kwargs)
                            if response:
                                break

                    if response is None:
                        wrapped_callback = self.make_view_atomic(callback)

                        try:
                            response = wrapped_callback(request, *callback_args, **callback_kwargs)

                        except Exception as e:
                            # If the view raised an exception, run it through exception
                            # middleware, and if the exception middleware returns a
                            # response, use that. Otherwise, reraise the exception.

                            for middleware_method in self._exception_middleware:
                                response = middleware_method(request, e)

```

**Comment by bufke** [comment]
Does anyone want to help on this? If not I'm going to just explicitly set the permission so that report builder at least runs. Restricting users based on permissions would be a non trivial problem to solve.

**Comment by leebrooks0** [comment]
What permission are you planning to set it to? If it is resstricted to admin users only then that would be great for me. Maybe the permissions could be passed in via a setting?

**Comment by bufke** [comment]
I made them IsAdminUser. If anyone needs something more configurable they should send a pull request.
