### ISSUE TITLE
python openpyxl error: ValueError: Invalid column index 0

### ISSUE THREAD

**Issue by Alix1** [burke-software/django-report-builder#142]
code：
from openpyxl import load_workbook
wb =load_workbook(filename=r'D:\testData\data2.xlsx')
# how many sheet
print('this data have work sheet:',wb.get_named_ranges())
print('the work sheet name is %s'%wb.get_sheet_names())
# get sheet 1
sheetNames = wb.get_sheet_names()
ws = wb.get_sheet_by_name(sheetNames[0 ])

print('work sheet name is ',ws.title)
print('work sheet row is ',ws.get_highest_row())
print('work sheet column is ',ws.get_highest_column())
# get the data

data_list =[]

for rn in range(ws.get_highest_row()):
    every_list=[]
    for cn in range(ws.get_highest_column()):
        rdata=ws.cell(row=rn,column=cn).value
        every_list=rdata
    data_list=every_list
print(data_list)

Error:

 return _STRING_COL_CACHE[idx]
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\eclipse\machine learning\src\testexcel.py", line 30, in <module>
    rdata=ws.cell(row=rn,column=cn).value
  File "C:\Python34\lib\site-packages\openpyxl\worksheet\worksheet.py", line 350, in cell
    column = get_column_letter(column)
  File "C:\Python34\lib\site-packages\openpyxl\utils\__init__.py", line 101, in get_column_letter
    raise ValueError("Invalid column index {0}".format(idx))
ValueError: Invalid column index 0

**Comment by Alix1** [comment]
anyone can help? please

**Comment by Alix1** [comment]
python 3.4

**Comment by grantjenks** [comment]
Can you upload data2.xlsx? It's hard to help without being to run the commands.

**Comment by bufke** [comment]
Sorry I didn't respond before. This seems like a openpyxl problem and not related to report builder. I'm going to close it, please reopen if I'm wrong here.
