### ISSUE TITLE
Add Support for Django 1.8

### ISSUE THREAD

**Issue by grantjenks** [burke-software/django-report-builder#144]
Report builder works great in a Django 1.7 project. But something is broken in a Django 1.8 project. The Model._meta API was standardized in Django 1.8. It would be great if this project moved to the new standard. There's a migration guide at https://docs.djangoproject.com/en/1.8/ref/models/meta/#migrating-old-meta-api

Though it says the old way of doing these was only deprecated, I've experienced issues with relation-fields. For some reason the api doesn't fetch the correct fields. Here's a snippet from a debug session that shows part of the problem:

    -> return self.dispatch(request, *args, **kwargs)
      /Users/grantj/repos/harvesthome/env27/lib/python2.7/site-packages/rest_framework/views.py(449)dispatch()
    -> response = handler(request, *args, **kwargs)
      /Users/grantj/repos/harvesthome/env27/lib/python2.7/site-packages/report_builder/api/views.py(82)post()
    -> self.path_verbose,)
    > /Users/grantj/repos/harvesthome/env27/lib/python2.7/site-packages/report_utils/mixins.py(482)get_fields()
    -> fields = get_direct_fields_from_model(new_model)
    (Pdb) l
    477  	                path_verbose = new_model.__name__.lower()
    478  	            else: # Indirect related field
    479  	                new_model = field[0].model
    480  	                path_verbose = new_model.__name__.lower()
    481  	
    482 B->	            fields = get_direct_fields_from_model(new_model)
    483  	
    484  	            custom_fields = get_custom_fields_from_model(new_model)
    485  	            properties = get_properties_from_model(new_model)
    486  	            app_label = new_model._meta.app_label
    487  	
    (Pdb) new_model
    <class 'crm.models.Client'>
    (Pdb) field
    (<OneToOneRel: crm.pregnancy>, None, False, False)
    (Pdb) field[0].model
    <class 'crm.models.Client'>
    (Pdb) field[0].to
    <class 'crm.models.Client'>

In the above session, Pregnancy is a model with a one-to-one-field reference to Client. When I build a report based on the Client, I see the pregnancy field in the related set. But if I click `pregnancy` then I don't see the Pregnancy fields. I see the Client fields. Because of this, the relations become cyclic and all the fields of related models are the same as the root model.

I traced it back to `report_utils.mixins.py:get_fields` but I could be off in the weeds. The function didn't seem to be working as intended.

**Comment by bufke** [comment]
Thanks for reporting. In report utils changing line 479 to related_model fixes it.

     else:
        new_model = field[0].related_model  
        path_verbose = new_model.__name__.lower()

No time to push a fix today, but soon. If you have time you could tell me if this breaks django 1.7.

**Comment by grantjenks** [comment]
Thanks!

**Comment by grantjenks** [comment]
Django 1.8 still doesn't work unfortunately. Try adding this unit test to `ReportBuilderTests`:

```
    def test_report_builder_related_fields(self):
        ct = ContentType.objects.get(model='place')
        response = self.client.post(
            '/report_builder/api/related_fields/', {
                'model': ct.id,
                'path': '',
                'field': 'restaurant'
            }
        )
        self.assertContains(response, '"field_name":"waiter"')
        self.assertContains(response, '"verbose_name":"waiter_set"')
        self.assertContains(response, '"path":"restaurant__"')
```

That will pass in Django 1.7 and fail in Django 1.8.

**Comment by bufke** [comment]
Is this the problem?
![screenshot from 2015-06-03 20 19 58](https://cloud.githubusercontent.com/assets/739307/7974297/f8acae38-0a2d-11e5-8998-d5f3546316ac.png)

**Comment by grantjenks** [comment]
Yep. It's not getting the related_fields correct. The unit test checks that
place has the correct fields. It should pass on 1.7 and fail on 1.8.

**Comment by saulshanabrook** [comment]
@grantjenks I have confirmed that your test case does pass in 1.7 and fails in 1.8. I will look into it.
