### ISSUE TITLE
Report Description not being saved

### ISSUE THREAD

**Issue by abhishekreddy1206** [burke-software/django-report-builder#145]
The description that we enter when creating a new report is somehow not being saved into the database.

**Comment by grantjenks** [comment]
I haven't had that problem. Did you check your settings?

**Comment by grantjenks** [comment]
Actually, I just noticed this myself. If I enter a description when creating a report from the admin interface, I think it works. But if I create a report from the reporting interface then it doesn't save.

**Comment by abhishekreddy1206** [comment]
Yeah! i looked at the code and realized that the serializer bringing the fields in the interface does not have the description field. I included it and it worked fine!

**Comment by grantjenks** [comment]
I'm new to Django-rest-framework. Could you point to what you mean or share a pull-request?

**Comment by abhishekreddy1206** [comment]
So only change i made was the following:

Navigate to site-packages > report_builder/api/serializers.py

Under ReportNestedSerializer add 'description' following into the fields.

**Comment by bufke** [comment]
If you send that as a pull request I'd be happy to merge it.
