### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by googaa** [burke-software/django-report-builder#146]
download didn't activate help me to fix this
![report_builder](https://cloud.githubusercontent.com/assets/11581354/7427806/24c0fd76-f016-11e4-90c1-07b981497493.png)

**Comment by bufke** [comment]
Could you provide some console output in the browser and on django? What errors are you getting?

**Comment by googaa** [comment]
no error just didnt activate and unicode problem

**Comment by bufke** [comment]
I'll need more info. What is the unicode problem? Is there a stack trace? Closing until more information in provided.

**Comment by googaa** [comment]
![unicode](https://cloud.githubusercontent.com/assets/11581354/8000097/850acaa8-0b88-11e5-8231-ab9d34fa1c3e.png)
unicode problem how to fix it

**Comment by googaa** [comment]
unicode problem how to fix it​
