### ISSUE TITLE
Django 1.8 related issue with REPORT_BUILDER_INCLUDE

### ISSUE THREAD

**Issue by epicdbadmin** [burke-software/django-report-builder#148]
Been working and troubleshooting Django Report Builder. Have looked through documentation but not very clear on specific setup. Can access Add Format page, but not save format or continue editing.

Can't add reports at all, throws field error. Not sure what else to do. Little to no support for this app yet. Do you have any resources that are a little more specific or have any suggestions on how to fix this issue, would be greatly appreciated. 

Thanks!

**Comment by bufke** [comment]
Could you post the error you get here? Thanks.

**Comment by heathernicoale** [comment]
Yes I've reinstalled it...

Error is cannot resolve 'name' choices: app_label, model, permission,
report.

I might have left out one choice... ive left my work desk for the evening.

Thank you!!!

**Comment by heathernicoale** [comment]
Here is the exact error
FieldError at /admin/report_builder/report/

Cannot resolve keyword 'name' into field. Choices are: app_label, id,
logentry, model, permission, report

Request Method: GET Request URL:
http://localhost:8000/admin/report_builder/report/ Django Version: 1.8
Exception Type: FieldError Exception Value:

Cannot resolve keyword 'name' into field. Choices are: app_label, id,
logentry, model, permission, report

Exception Location:
/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py in
names_to_path, line 1386 Python Executable: /usr/bin/python


*~Finish Strong~*


*Heather N. JohnsonStudent ID# - 1092569*

*(828) 777-3793*


*Enjoy the moment, live for today.*

*Capture the joys along the way.*

**Comment by bufke** [comment]
Is that the entire stack trace? Does it say what file and line the "Cannot resolve keyword 'name' into field" error is happening in? Are you sure you are on the latest version? Django 1.8 should be supported but perhaps there are still issues.

**Comment by heathernicoale** [comment]
Yes, I'm using 1.8

Thank you for replying by the way. I really want to get this working, it
looks like a great app! I can get to the add page, and it displays the
models I have. But when I try to add, I get this:


This was the first error I get:

ProgrammingError at /admin/report_builder/report/add/

(1146, "Table 'epic_test2.report_builder_report' doesn't exist")

Request Method: POST Request URL:
http://localhost:8000/admin/report_builder/report/add/ Django Version: 1.8
Exception Type: ProgrammingError Exception Value:

(1146, "Table 'epic_test2.report_builder_report' doesn't exist")

Exception Location: /usr/lib/python2.7/dist-packages/MySQLdb/connections.py
in defaulterrorhandler, line 36 Python Executable: /usr/bin/python Python
Version: 2.7.6 Python Path:

['/home/dbadmin/django/epicapi',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-i386-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']

Server time: Wed, 13 May 2015 14:34:24 +0000

The second one is this:

Cannot resolve keyword 'name' into field. Choices are: app_label, id,
logentry, model, permission, report

 Request Method: POST  Request URL:
http://localhost:8000/admin/report_builder/report/add/  Django
Version: 1.8  Exception
Type: FieldError  Exception Value:

Cannot resolve keyword 'name' into field. Choices are: app_label, id,
logentry, model, permission, report

 Exception Location:
/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py
in names_to_path, line 1386  Python Executable: /usr/bin/python  Python
Version: 2.7.6  Python Path:

['/home/dbadmin/django/epicapi',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-i386-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']

 Server time: Wed, 13 May 2015 14:35:36 +0000  Here is the traceback for
the second Error Message:


Environment:


Request Method: POST
Request URL: http://localhost:8000/admin/report_builder/report/add/

Django Version: 1.8
Python Version: 2.7.6
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'factories',
 'machines',
 'employees',
 'report_builder')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware')


Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py"
in get_response
  132.                     response = wrapped_callback(request,
*callback_args, **callback_kwargs)
File
"/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py" in
wrapper
  616.                 return self.admin_site.admin_view(view)(*args,
**kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py" in
_wrapped_view
  110.                     response = view_func(request, *args, **kwargs)
File
"/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py"
in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py"
in inner
  233.             return view(request, *args, **kwargs)
File
"/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py" in
add_view
  1516.         return self.changeform_view(request, None, form_url,
extra_context)
File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py" in
_wrapper
  34.             return bound_func(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py" in
_wrapped_view
  110.                     response = view_func(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py" in
bound_func
  30.                 return func.__get__(self, type(self))(*args2,
**kwargs2)
File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py" in
inner
  145.                     return func(*args, **kwargs)
File
"/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py" in
changeform_view
  1458.             form = ModelForm(request.POST, request.FILES,
instance=obj)
File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py" in
__init__
  336.                     formfield.queryset =
formfield.queryset.complex_filter(limit_choices_to)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in
complex_filter
  715.             return self._filter_or_exclude(None, **filter_obj)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in
_filter_or_exclude
  697.             clone.query.add_q(Q(*args, **kwargs))
File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py"
in add_q
  1301.         clause, require_inner = self._add_q(where_part,
self.used_aliases)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py"
in _add_q
  1328.                     current_negated=current_negated,
connector=connector, allow_joins=allow_joins)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py"
in build_filter
  1150.         value, lookups, used_joins =
self.prepare_lookup_value(value, lookups, can_reuse, allow_joins)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py"
in prepare_lookup_value
  997.             value = value()
File "/usr/local/lib/python2.7/dist-packages/report_builder/models.py" in
_get_allowed_models
  35.             models =
models.filter(name__in=settings.REPORT_BUILDER_INCLUDE)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in
filter
  679.         return self._filter_or_exclude(False, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in
_filter_or_exclude
  697.             clone.query.add_q(Q(*args, **kwargs))
File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py"
in add_q
  1301.         clause, require_inner = self._add_q(where_part,
self.used_aliases)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py"
in _add_q
  1328.                     current_negated=current_negated,
connector=connector, allow_joins=allow_joins)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py"
in build_filter
  1144.         lookups, parts, reffed_aggregate =
self.solve_lookup_type(arg)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py"
in solve_lookup_type
  1030.         _, field, _, lookup_parts =
self.names_to_path(lookup_splitted, self.get_meta())
File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py"
in names_to_path
  1386.                                      "Choices are: %s" % (name, ",
".join(available)))

Exception Type: FieldError at /admin/report_builder/report/add/
Exception Value: Cannot resolve keyword 'name' into field. Choices are:
app_label, id, logentry, model, permission, report






*~Finish Strong~*


*Heather N. JohnsonStudent ID# - 1092569*

*(828) 777-3793*


*Enjoy the moment, live for today.*

*Capture the joys along the way.*

**Comment by heathernicoale** [comment]
NOTE: I only get the second error if I try to do an REPORT_BUILDER_INCLUDE.

I got the first error as soon as I downloaded it. And I have migrated
everything and synced the databases, so I'm not sure of what it can't find.

The second error may not even be valid if I can figure out the first one.

Thanks!!!

~Heather


*~Finish Strong~*


*Heather N. JohnsonStudent ID# - 1092569*

*(828) 777-3793*


*Enjoy the moment, live for today.*

*Capture the joys along the way.*

**Comment by heathernicoale** [comment]
I think it's the first error that's the main problem. The second error only
came when I tried to "fix" it. I'm sorry to keep pestering you. I don't
have ANYONE to bounce ideas off of or anyone who knows anything about
python or Django. So I'm kind of craving the collaboration in this problem.

If I migrate is report builder supposed to create a table? Or am I supposed
to do that?



*~Finish Strong~*


*Heather N. JohnsonStudent ID# - 1092569*

*(828) 777-3793*


*Enjoy the moment, live for today.*

*Capture the joys along the way.*

**Comment by waqasjaved160** [comment]
Did you run python manage.py migrate after installing the report builder package ?

**Comment by heathernicoale** [comment]
Yes I did. Thats what doesn't make sense. Ive tried it three different
times now.

**Comment by bufke** [comment]
The REPORT_BUILDER_INCLUDE issue is a 1.8 related problem. Thanks for reporting that. In addition I noticed it doesn't work great when clicking New Report in the /report_builder interface.

As for tables - I'm not sure. Certainly sounds like a migration issue where the database is not made but I don't know why that would happen.

**Comment by farzian** [comment]
i had the same problem with django 1.8 (today i installed django-report-builder using pip). i uninstalled it using pip and re-installed it manually by downloading latest code from github. that error disappeared but another error raised: 

TypeError at /admin/report_builder/report/
'staticmethod' object is not iterable
Request Method:	GET
Request URL:	http://127.0.0.1:8000/admin/report_builder/report/
Django Version:	1.8
Exception Type:	TypeError
Exception Value:	
'staticmethod' object is not iterable
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py in get_prep_lookup, line 729
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/usr/local/lib/python2.7/dist-packages/django_report_builder-3.1.7-py2.7.egg',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']

---------------------

also before that i had another problem: in the report creation page (fields, filters, ...) calling to api/fields url by angularJs got 500 error with no useful information. so no field could be selected to create report. also grappelli admin theme dose not applied to some pages ! (i'm using grappelli for my admin)

**Comment by bufke** [comment]
I haven't released the latest code to pypi. My attempt to fix the 2.7 issue introduced a regression.

**Comment by bufke** [comment]
Should be fixed now. @farzian you could try the latest git master to confirm. If I don't hear of any issues I'll release it to pypi very soon. I added a unit test to ensure the admin page at least loads which would have caught this issue.

**Comment by farzian** [comment]
thanks @bufke . that error seems fixed. but as i said there is another error on report creation page. it doesn't show any field of related model in the page, so i can't select any field to make a report. this is what i see in the browser's console:

POST http://127.0.0.1:8000/report_builder/api/related_fields/ 500 (INTERNAL SERVER ERROR)b @ angular.js:9818m @ angular.js:9619$get.f @ angular.js:9335(anonymous function) @ angular.js:13175$get.l.$eval @ angular.js:14388$get.l.$digest @ angular.js:14204$get.l.$apply @ angular.js:14493l @ angular.js:9650O @ angular.js:9840w.onload @ angular.js:9781


POST http://127.0.0.1:8000/report_builder/api/fields/ 500 (INTERNAL SERVER ERROR)b @ angular.js:9818m @ angular.js:9619$get.f @ angular.js:9335(anonymous function) @ angular.js:13175$get.l.$eval @ angular.js:14388$get.l.$digest @ angular.js:14204$get.l.$apply @ angular.js:14493l @ angular.js:9650O @ angular.js:9840w.onload


i have django-rest-framework and it works properly for my rest APIs.

**Comment by lvngd** [comment]
@heathernicoale do you have report_builder in your INSTALLED_APPS?

**Comment by heathernicoale** [comment]
I do :)

**Comment by bufke** [comment]
@farzian what version of django, python, and django rest framework are you using? 

The 500 error should be visible with a stack trace. Look in your browsers developers tools in the networking tab. If you could paste that it would be a huge help. Thanks.

**Comment by farzian** [comment]
pythn 2.7.6 -- django 1.8 -- lastest version of rest framework.
sure, it seems it is unicode error, but i'm using rest framework with unicode data without problem ! stack trace is:

UnicodeDecodeError at /report_builder/api/fields/
'ascii' codec can't decode byte 0xd8 in position 1: ordinal not in range(128)
Request Method:	POST
Request URL:	http://127.0.0.1:8000/report_builder/api/fields/
Django Version:	1.8
Exception Type:	UnicodeDecodeError
Exception Value:	
'ascii' codec can't decode byte 0xd8 in position 1: ordinal not in range(128)
Exception Location:	/usr/lib/python2.7/json/encoder.py in encode, line 210
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/usr/lib/python2.7/dist-packages',
 '/usr/local/lib/python2.7/dist-packages/django_report_builder-3.1.7-py2.7.egg',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']

Unicode error hint

The string that could not be encoded/decoded was: "������
Traceback Switch back to interactive view

/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py in get_response
                            response = response.render() ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/template/response.py in render
                        self.content = self.rendered_content ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/rest_framework/response.py in rendered_content
                    ret = renderer.render(self.data, media_type, context) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/rest_framework/renderers.py in render
                        separators=separators ...
▶ Local vars
/usr/lib/python2.7/json/__init__.py in dumps
                    sort_keys=sort_keys, **kw).encode(obj) ...
▶ Local vars
/usr/lib/python2.7/json/encoder.py in encode
                    return ''.join(chunks) ...
▶ Local vars

**Comment by bufke** [comment]
I tried it with python 2.7 but can't reproduce this. I don't see report_builder in that stack trace. Are you using any non default rest framework settings?

**Comment by farzian** [comment]
i have just set these settings in settings.py: 

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly'
    ]
}

and also have enabled 'rest_framework' and 'rest_framework.authtoken' apps in INSTALLED_APPS.

**Comment by knixeur** [comment]
@farzian I had that same problem yesterday, it turned to be related to a verbose_name in a field which wasn't explicitly unicode ( u' )

**Comment by bufke** [comment]
Cleaning up tickets. Reopen if mistakenly closed.
