### ISSUE TITLE
How about more lightweight way to run background reports?

### ISSUE THREAD

**Issue by andybak** [burke-software/django-report-builder#156]
Celery plus all it's requirements is a huge dependency to inflict just to run a background task.

You could probably get away with something as simple as https://github.com/defrex/django-after-response (or just spawn a subprocess yourself).

If that doesn't do the trick then Huey - https://github.com/coleifer/huey - is a step up. It still needs Redis - but it's a lot less effort to install and maintain than Celery.

**Comment by bufke** [comment]
We already support two methods (Celery and synchronous reports). I'm not going to commit more time to support another option. I would accept a pull request. If you want to work on this please open this issue back up.
