### ISSUE TITLE
UtilityFunctionTests.test_get_relation_fields_from_model broken in Django 1.7

### ISSUE THREAD

**Issue by grantjenks** [burke-software/django-report-builder#158]
UtilityFunctionTests.test_get_relation_fields_from_model fails in Django 1.7. Here's `names` from a debug session:

```
-> self.assertTrue('displayfield' in names)
(Pdb) names
['report_builder:displayfield', 'report_builder:filterfield', 'root_model', 'starred', 'user_created', 'user_modified']
```

In Django 1.8 the name does not have the `report_build:` prefix so this passes.

Also Issue #144 should be re-opened but I don't have permission to do so. There's a unit-test there that highlights another Django 1.8 issue.

**Comment by bufke** [comment]
Does this cause problems for 1.7 users or is it just the unit test fails in 1.7 (which I could ignore)?

**Comment by grantjenks** [comment]
I don't know whether it causes problems. I didn't understand the test.

**Comment by bufke** [comment]
Cleaning up tickets. Reopen if mistakenly closed.
