### ISSUE TITLE
Differentiate between filters and fields to display

### ISSUE THREAD

**Issue by AbhiAgarwal** [burke-software/django-report-builder#166]
On the product I am working on we needed a way to distinguish between a `filter` and a `display` field. Basically the ability to filter using some columns and display some columns. 

The solution I wanted to implement would be to add a new configuration field called `filter` alongside `fields`, `exclude`, and `extra`. This configuration field would just be the fields that the user would want to filter using. Then this will be useful on the end-point. The items in the `/fields` end-point would just have a row called `is_filter`. This would just be true/false depending on if that variable will be something they would filter using. 

The idea is just to add:

```python
'is_filter': True if filters and new_field.name in filters else False,
```
into the each loop in class `FieldsView` in `views.py`.

I was thinking about the `fields` variable to be a superset of the `filter` variable. You should be able to display everything you filter by. 

I wanted thoughts on this issue as I think it would be helpful for others as well.

**Comment by grantjenks** [comment]
`FieldsView` has no `filters` variable. I don't understand your proposal.

When you speak of fields do you mean `DisplayField` and `FilterField` as defined in `models.py` or do you mean Django ORM fields? I don't believe Django models have filter fields though certainly the ORM allows you to filter with querysets.

**Comment by AbhiAgarwal** [comment]
@grantjenks My apologies. Let me be more clear. I want to add a configuration called `filters` (similar to the configuration `fields`) that is defined in the model that the user specifies. 

The configuration `filters` is defined as `filters = getattr(meta, 'filters', None)` in the `FieldsView` class in `views.py`. The user would just define it as a tuple of all the fields that can be filtered with. In this example:

```python
class Foo(models.Model):
    char_field = models.CharField(max_length=50, blank=True)
    char_field2 = models.CharField(max_length=50, blank=True)
    char_field3 = models.CharField(max_length=50, blank=True)

    class ReportBuilder:
        fields = ('char_field', 'char_field3')
        filters = ('char_field3')
```

Through this I am trying to add to the `/fields` end-point the idea that there can be a distinction between the fields that are displayed and fields that can be filtered by. This is not making any large change, but just adding functionality. If the filters field is missing or empty then all the fields will be fields that can be filtered by.  

This is just for an increase in front-end functionality. I'm not attempting to change any backend code. I wrote the [functionality](https://github.com/AbhiAgarwal/django-report-builder/commit/c0c22fd6387cf0b5e4693c0c74711f825fb3fe45) out if you're interested. I haven't sent a pull-request yet because I wanted to discuss the idea before-hand.

**Comment by grantjenks** [comment]
I hadn't realized the current system supports `class ReportBuilder:` type meta-fields. I don't use those myself so David will have to comment.
