### ISSUE TITLE
Support for external field types

### ISSUE THREAD

**Issue by AbhiAgarwal** [burke-software/django-report-builder#192]
I am running into issues where I'm not sure how to support field types that are from external packages. Types such as [MoneyField](https://github.com/django-money/django-money). 

I was curious if anyone else had this problem before, and how people solved it.

**Comment by AbhiAgarwal** [comment]
I found the issue for this. `field_data['fields'].remove(field)` removes the first element. I had a `budget` and `budget_currency`, and the `budget` was getting removed because it was before `budget_currency`. I didn't expect this to happen, but I'll look into it and send a pull request.

**Comment by grantjenks** [comment]
Can we close this now that #193 has been merged?
