### ISSUE TITLE
NoReverseMatch at /admin/report_builder/report/ ... Reverse for 'report_download_xlsx' ... not found.

### ISSUE THREAD

**Issue by grantjenks** [burke-software/django-report-builder#203]
Reverse for 'report_download_xlsx' with arguments '(15,)' and keyword arguments '{}' not found. 0 pattern(s) tried: []

Looks like the bug is here: https://github.com/burke-software/django-report-builder/blob/master/report_builder/models.py#L393

Sorry I don't have time to create a pull request.

When this is fixed I can test the release candidate on my end.

**Comment by joeestes86** [comment]
I'm getting this error as well.  Is there a resolution?  Thanks!

**Comment by bufke** [comment]
I released a new RC too. Hopefully the last.

**Comment by jonathanmorgan** [comment]
Is it easy to install a release candidate? I'd like to test out 3.2rc4, but am not sure how to do that.

**Comment by jonathanmorgan** [comment]
Figured it out, capturing here for when I wind up here again:
- to see all versions: `pip install django-report-builder==123456` (just use a rediculously high version number)
- to install a particular version from list: `pip install django-report-builder==3.2.0rc4`
- in this case, was "3.2.0rc4".

**Comment by akelley-kemple** [comment]
Yeah just set it in your requirements file like
django-report-builder==3.2rc4

David Burke
davidmburke.com

**Comment by jonathanmorgan** [comment]
3.2.0rc4 resolved this problem for my client.  They are going to be running some reports in next day or so, will let you know if there are any problems.  Thanks!

**Comment by mandywil** [comment]
Thank you -- this was a life-saver!
