### ISSUE TITLE
[minor] - Update the quickstart manual

### ISSUE THREAD

**Issue by vadimdne** [burke-software/django-report-builder#205]
Need to update the quickstart manual:
https://django-report-builder.readthedocs.org/en/latest/quickstart/

> INSTALLATION 
> ...
> 4. Ensure django.core.context_processors.static and django.core.context_processors.media are in TEMPLATE_CONTEXT_PROCESSORS

To reflect the changes in Django 1.8 - context processors are moved to OPTIONS.

**Comment by bufke** [comment]
Sure - would you mind submitting a pull request with the documentation change and the settings changed in the [demo project](https://github.com/burke-software/django-report-builder/blob/master/report_builder_demo/settings.py)?
