### ISSUE TITLE
Django report builder doesn't show anything but loading and never finish

### ISSUE THREAD

**Issue by bykof** [burke-software/django-report-builder#207]
Hey Guys,
I installed Django Report Builder in my Django project. The developer server starts good but if I try to access 127.0.0.1:8000/report_builder on Chrome the webpage doesn't load and it looks like it is in an endless loop and on Firefox the browser freezes. 
The debug output of the django server prints following:
[21/Sep/2015 10:03:40] "GET /report_builder/ HTTP/1.1" 200 2595
[21/Sep/2015 10:03:40] "GET /report_builder/report_builder/partials/home.html HTTP/1.1" 200 2595

Hope the information helps you!

**Comment by bufke** [comment]
Did you double check every step in the install instructions? http://django-report-builder.readthedocs.org/en/latest/quickstart/

The included sample project should work - maybe you can start there and see what is different. If you find anything confusing in the install instructions please let me know.
