### ISSUE TITLE
Couple of issues:

### ISSUE THREAD

**Issue by gkirkpatrick** [burke-software/django-report-builder#208]
First, I see this in my dev-server log:
"GET /report_builder/%7B%7B%20static('report_builder/img/new/download.svg')%20%7D%7D HTTP/1.1" 200 14976

When the edit report page loads up. This looks like the URL is being generated on the fly somewhere, but I couldn't find it in the code. Maybe there needs to be a safe filter somewhere?

Django 1.8.4, most recent commit of DRB. I

My second issue, which I wonder if it's related is that the whole app looks like it is missing some CSS. 

I've looked through all the issues on the site, and I'm pretty sure I've covered all the bases. I might have something wrong with how I handle static files? 

![screen shot 2015-09-22 at 4 44 06 pm](https://cloud.githubusercontent.com/assets/2320357/10031108/55ceea96-6149-11e5-9533-fb4d7baffbde.png)

**Comment by bufke** [comment]
Try 3.2 - I just released it (it was in RC before). 

A lot of people have been unhappy with the UI - I don't think I can make anything better. Graphic design isn't my strong suit. If you want to propose a dramatic change please post it here first. Personally I don't mind it but I get a fair amount of emails from people thinking it's strange so I'm up for new ideas.
