### ISSUE TITLE
Filter capabilities

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [burke-software/django-report-builder#213]
Hi,

I'm aware that the filters are for "and" statement but is an "or" statement possible regarding the filters?

**Comment by grantjenks** [comment]
It is not.

But there's a work-around for foreign keys. You can use the "in" operator and enter a comma-separated list of model ids.

**Comment by Dean-Christian-Armada** [comment]
OK, thanks for the advice will check that option out

**Comment by bufke** [comment]
I've thought of this problem before - the ideal solution I think is adding grouping and OR support. Django ORM supports this. Adding the UI elements and the backend logic to support it would be a pretty big task though.

**Comment by Dean-Christian-Armada** [comment]
Yes, There is only one web app thaat I have seen with that kind of capability which is the responsys email blasting. I agree that would be a pretty big task to as well. But are you planning to add that capability in the future?

**Comment by bufke** [comment]
Honestly I probably won't be unless I can convince a client to fund it. It's possible but it's hard to get any major changes funded.

**Comment by Dean-Christian-Armada** [comment]
Ok, noted on this one and thanks
