### ISSUE TITLE
You upgraded my Django

### ISSUE THREAD

**Issue by andybak** [burke-software/django-report-builder#227]
Installing collected packages: django, django-report-builder
      Found existing installation: Django 1.8.11
        Uninstalling Django-1.8.11:
          Successfully uninstalled Django-1.8.11
      Found existing installation: django-report-builder 3.3.0
        Uninstalling django-report-builder-3.3.0:
          Successfully uninstalled django-report-builder-3.3.0
      Running setup.py install for django-report-builder ... done
    Successfully installed django-1.9.4 django-report-builder-3.3.0

Please don't! Even if you're not compatible with Django 1.8 this should be handled by raising an error or warning via the system check framework. I noticed psycog in requirements also - which seems odd.

**Comment by bufke** [comment]
Can you do a pull request and just make sure travis still passes and gets the right version? I think django can just be removed outright from setup.py. Also this project could use more maintainers if you are interested.

**Comment by andybak** [comment]
> Can you do a pull request and just make sure travis still passes and gets the right version?

At the moment I'm finding accessing the report builder view just locks up my browser. I didn't have time to dig into why so I moved on. If you've got any suggestions then I might take another look.

> Also this project could use more maintainers if you are interested.

I'm very interested in the concept and I think there's a real need for something like report builder. However to my way of thinking, angular is a pretty heavy dependency and not something I'm really keen on supporting. Would it be a mammoth task to replace it with something less frameworky?

**Comment by bufke** [comment]
I haven't seen any lock up issues myself. I test against Firefox and Chrome. If you find something reproducible let me know.

I did a jquery version a long time ago and it become a huge mess to maintain - some of that can be blamed on my front end inexperience. I found angular very helpful. I think the nature of the program means it has to be a single page with api requests. I'm sure the angular version could be improved and I'm open to a different front end or a replacement but I would need someone doing that with a huge amount of time to put into it and maintain it.

I'm happy to keep maintaining this project given it's relative popularity but I just can't commit time to major changes. If I get a new client who wants to invest in it that changes things but at this time it hasn't happened. Looking at your github profile it looks you like work for an agency too - the best idea I have is to find a client who wants this and can invest in improvements and then charge a technical debt markup to make less visible improvements. I'd be happy to help as a paid consultant.

**Comment by andybak** [comment]
If I get a chance I'll try report builder out on a simpler project to see if it's reproducible. 

I understand your concerns about complex jQuery apps - it's just that Angular elicits strong emotions itself ;-) I found it didn't 'fit my brain' so to speak.

If a commercial requirement comes along I'll get in touch.

**Comment by bufke** [comment]
Next release I'll require webpack too :P jk
