### ISSUE TITLE
Going to `/report_builder/` hangs Django?

### ISSUE THREAD

**Issue by ckcollab** [burke-software/django-report-builder#234]
Heyo! Thanks for releasing this, I was super excited to try it out, but going to `/report_builder/` completely hangs django runserver? Not sure anyone else is experiencing this, so maybe I missed something?

1) I pip installed it
2) added to installed apps
3) Added URL
4) Was able to go to URL without a problem, but page hung
5) Went to admin, tried adding a report, selected a model, was redirected to `/report_builder/` but that hangs still :)

Appreciate all the work!

**Comment by vitorfragoso** [comment]
Same here! :(

**Comment by ckcollab** [comment]
I know @9jevans9 figured it out, I can't remember what it was...

**Comment by bufke** [comment]
Can you double check you followed the install steps - including the context processors part? 

http://django-report-builder.readthedocs.io/en/latest/quickstart/

**Comment by ckcollab** [comment]
Ah! Yeah I think that was it, thanks @bufke :D
