### ISSUE TITLE
RemovedInDjango110Warning is fixed, but not released?

### ISSUE THREAD

**Issue by ckcollab** [burke-software/django-report-builder#235]
Heyo! Thanks for all the work on this, sorry to bug you about something so trivial but I was hoping you could deploy this fix to pypi? Maybe there are some other changes you're waiting on before publishing these changes, if so, that's cool :D

**Comment by bufke** [comment]
I just released an update to fix this. I see there are a few more errors in the demo app I want to fix too. Since 1.10 is coming out soon feel free to open any specific incompatibility issues.

**Comment by ckcollab** [comment]
thanks so much!
