### ISSUE TITLE
Change log?

### ISSUE THREAD

**Issue by ckcollab** [burke-software/django-report-builder#244]
I was wondering if there was a changelog to see what has changed since 3.4.1 to 3.4.3?

Thanks for all the work on this, really appreciate it!

**Comment by bufke** [comment]
Do you think git tags be sufficient? That way it's easier to see what changes made it into a release. Then just continue noting major changes on the README.

**Comment by ckcollab** [comment]
I think so? Not sure... :)

**Comment by bufke** [comment]
https://github.com/burke-software/django-report-builder/blob/master/CHANGELOG

**Comment by bufke** [comment]
also thank you for the suggestion.
