### ISSUE TITLE
Related Fields in Django 1.10

### ISSUE THREAD

**Issue by marialaraa** [burke-software/django-report-builder#255]
The problem is when using a model with `ManyToManyField` or a `ForeignKey` related. When I try to access to the related object in the sidebar, the fields of this model don't appear and I get this error:

 ` File "lib/python3.4/site-packages/report_builder/mixins.py", line 557, in get_fields
    new_model = field.related.model
AttributeError: 'ForeignKey' object has no attribute 'related' `

or: 

`  File "lib/python3.4/site-packages/report_builder/mixins.py", line 557, in get_fields
    new_model = field.related.model
AttributeError: 'ManyToManyField' object has no attribute 'related'`

I could solve the problem with a custom version, 
https://github.com/devartis/django-report-builder/blob/master/report_builder/mixins.py#L555
Changing the `if` condition to be like the `else` part.
The same here:
https://github.com/devartis/django-report-builder/blob/master/report_builder/utils.py#L202
But I also check if the field is empty because it could exist with nothing. 

The proyect use Django 1.10 and Python 3.

**Comment by Resousse** [comment]
Same here, I followed @marialaraa methods! It works :)

**Comment by bufke** [comment]
Anyone know if https://github.com/burke-software/django-report-builder/pull/257 resolves this? It just needs a unit test to be accepted.

**Comment by piyushlearn** [comment]
@marialaraa For me, Report Builder is not able to identify any models. When I get to add report, the Root Model dropdown for me is empty. I am on Django 1.10, Python 3.5 and django-report-builder 3.4.4.

**Comment by CoinBR** [comment]
Same here

**Comment by pyfection** [comment]
I have the same issue. Is this project not maintained anymore? This is a really huge issue with apparently an easy fix.

**Comment by bufke** [comment]
@pyfection I'm no longer actively adding features to this anymore but I'm happy to merge things in. Be the pull request you want to see in the world :)

I do think it's a pretty easy fix - just confirm the fix and write a test demonstrating that it's effective and that it doesn't break any currently supported django version.

**Comment by bufke** [comment]
I wrote a unit test for this and fixed it. Using tox now to make it easier to test multiple versions of django. Thanks for reporting!
