### ISSUE TITLE
All API calls return 403 Forbidden CSRF Failed: CSRF token missing or incorrect."

### ISSUE THREAD

**Issue by kpnunni** [burke-software/django-report-builder#280]
Using
Django 1.11.0
Rest Framework 3.7
Python 3.5.3

After installation the report builder shows up but all api calls seem to return forbidden. The user is an admin and have all permissions assigned. Couldn't figure out what I'm missing here.

![screenshot from 2018-01-05 15-22-33](https://user-images.githubusercontent.com/387662/34604129-bc707596-f22c-11e7-98da-761192a7bcb5.png)
![screenshot from 2018-01-05 15-23-11](https://user-images.githubusercontent.com/387662/34604132-be7e4af2-f22c-11e7-9a45-bb7b98774f85.png)
![screenshot from 2018-01-05 15-23-30](https://user-images.githubusercontent.com/387662/34604135-c074cd72-f22c-11e7-9079-a8c923069864.png)

**Comment by kpnunni** [comment]
This is my REST_FRAMEWORK Configuration

`REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework_social_oauth2.authentication.SocialAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser'
    ),
    'DEFAULT_METADATA_CLASS': 'rest_framework.metadata.SimpleMetadata'
}`

**Comment by Bulletninja** [comment]
Did you have any luck solving this?

**Comment by bufke** [comment]
Can someone test this with 5.0? I may be fixed since we rewrote the frontend. I was never able to reproduce so I can't really verify that.
