### ISSUE TITLE
django-report-builder==6.1 failed to load static files 

### ISSUE THREAD

**Issue by Ritace** [burke-software/django-report-builder#301]
python==3.6.3 and django==2.0.8
Upon creating new django report and while editing the report in url 
http://localhost:8000/report_builder/report/2 or http://localhost:8000/report_builder/report/2
The browser throws 
```
Failed to load resource: the server responded with a status of 404 (Not Found)
polyfills.bundle.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
styles.bundle.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
main.bundle.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
styles.bundle.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```
I have run collectstatic and also added  'django.template.context_processors.static' and            'django.template.context_processors.media' in context processors.

**Comment by bufke** [comment]
Is there a reason you need to use version 6.1 and not the latest 6.2.2?

**Comment by Ritace** [comment]
I saw work in progress in the description for 6.2. So, I thought using version 6.1 would have been better.

**Comment by bufke** [comment]
Ah I updated this. I think I was waiting for celery to be updated to fully say we support python 3.7 but this never happened.
