### ISSUE TITLE
[select|prefetch]_related would be nice

### ISSUE THREAD

**Issue by caitifbrito** [burke-software/django-report-builder#58]
Hello folks,
    We use this project integrated with our [DjangoHstoreFlattenFields](https://github.com/multmeio/django-hstore-flattenfields), that support dynamic_fields in PostgreSQL like declared fields, and both together are so nice. But we have millions rows to relate and manipulate.. With manually reports we take care relations at ORM to prevent so many db hits, but with django-report-builder we can't perform these prefetch and select related.. Any solution for it!?  Thanks and congratulations for the project

**Comment by bufke** [comment]
Would be nice - but we have enough wish list items. Reopen if you want to work on this.
