### ISSUE TITLE
AttributeError on one Related Field blocks all others in related Model

### ISSUE THREAD

**Issue by bhaugen** [burke-software/django-report-builder#64]
Getting AttributeError on a photo field.  It's a ThumbnailerImageField.
"attribute can only be accessed from instances"

Don't care if it is included in reports anyway, but it is preventing all the other fields in the related Expand Related Fields Model from being expanded.

Would be good to either:
a) just bypass fields that give AttributeErrors, or
b) add a REPORT_BUILDER_EXCLUDE_FIELD setting.

**Comment by bufke** [comment]
Reopen if anyone thinks this is a report builder problem and has a potential solution.
