### ISSUE TITLE
Ability to quickly copy fields from 'Report Display Fields' tab to 'Report Filters' 

### ISSUE THREAD

**Issue by shirleyleu** [burke-software/django-report-builder#82]
Users take the time to select fields on the 'Report Display Fields' tab, and if they want to quickly apply filters, they are forced to take the time again to select the same fields under the 'Report Filters' tab.

A checkbox or button with 'Copy Display Fields' could be included and located near or under 'Drag fields here' in the 'Report Filters' tab.

**Comment by bufke** [comment]
I don't find this particularly useful
